#!/bin/bash
# build.sh — unifont-hex (Layer 1: Font data, no PVE deps)
#
# GNU Unifont — hex format font data used by vncterm for terminal rendering.
# Downloaded from GNU mirror.
# Install is a simple copy of hex font files.
#
# Adapted from proxmox-nixos (pkgs/unifont/default.nix):
#   - Nix: stdenv.mkDerivation, download from mirror://gnu/unifont/
#   - Nix makeFlags: USRDIR=., DESTDIR=$(out)
#   - AlmaLinux: install hex file + wchardata.c to /usr/share/unifont/
#
# Environment (injected by build-chain.yml):
#   VERSION, COMMIT, SHORT, TARGET_ID, TARGET_ARCH,
#   TARGET_CFLAGS, TARGET_CXXFLAGS, SOURCE_DISTRO
set -euo pipefail

PKG_NAME="unifont-hex"
UNIFONT_VERSION="17.0.03"
UNIFONT_URL="https://ftp.gnu.org/gnu/unifont/unifont-${UNIFONT_VERSION}/unifont-${UNIFONT_VERSION}.tar.gz"

# ------------------------------------------------------------------
# 1. Download source from GNU
# ------------------------------------------------------------------
echo "=== [$PKG_NAME] Downloading source from GNU ==="
WORKDIR="/tmp/src/${PKG_NAME}"
rm -rf "$WORKDIR"
mkdir -p "$WORKDIR"
curl -L -o "/tmp/${PKG_NAME}.tar.gz" "$UNIFONT_URL"
tar xzf "/tmp/${PKG_NAME}.tar.gz" -C "/tmp/src"
mv "/tmp/src/unifont-${UNIFONT_VERSION}" "$WORKDIR" 2>/dev/null || true
cd "$WORKDIR"

# ------------------------------------------------------------------
# 2. Build (extract hex font data)
# ------------------------------------------------------------------
echo "=== [$PKG_NAME] Preparing font data ==="
# The hex file and wchardata.c are generated by the unifont Makefile
# For vncterm, we need unifont.hex and wchardata.c
make -j"$(nproc)" hex || true

# ------------------------------------------------------------------
# 3. Install to staging root
# ------------------------------------------------------------------
echo "=== [$PKG_NAME] Installing to staging root ==="
STAGE="/tmp/pkg/${PKG_NAME}"
rm -rf "$STAGE"
mkdir -p "$STAGE/root/usr/share/unifont" "$STAGE/meta"

# Copy hex font file (used by vncterm)
if [[ -f "unifont.hex" ]]; then
    cp unifont.hex "$STAGE/root/usr/share/unifont/"
elif [[ -f "font/plane00/unifont.hex" ]]; then
    cp font/plane00/unifont.hex "$STAGE/root/usr/share/unifont/"
fi

# Copy wchardata.c (used by vncterm for wide character rendering)
if [[ -f "wchardata.c" ]]; then
    cp wchardata.c "$STAGE/root/usr/share/unifont/"
fi

# ------------------------------------------------------------------
# 4. Determine version
# ------------------------------------------------------------------
PKG_VERSION="${UNIFONT_VERSION}+${SHORT:-git}"

# ------------------------------------------------------------------
# 5. Write meta/ files
# ------------------------------------------------------------------
echo "$PKG_NAME"               > "$STAGE/meta/name"
echo "$PKG_VERSION"            > "$STAGE/meta/version"
echo "${TARGET_ARCH:-x86_64}"  > "$STAGE/meta/arch"
echo "GNU Unifont — hex format font data for vncterm" > "$STAGE/meta/description"
echo "Proxmox"                  > "$STAGE/meta/maintainer"
echo "rpm"                      > "$STAGE/meta/source_format"

cat > "$STAGE/meta/depends" << 'EOF'
EOF

# ------------------------------------------------------------------
# 6. Package as .pkg.tar
# ------------------------------------------------------------------
echo "=== [$PKG_NAME] Creating .pkg.tar ==="
cd "$STAGE"
tar cf "/workspace/${PKG_NAME}_${PKG_VERSION}_${TARGET_ARCH:-x86_64}.pkg.tar" meta root

echo "=== [$PKG_NAME] Done ==="
echo "Artifact: /workspace/${PKG_NAME}_${PKG_VERSION}_${TARGET_ARCH:-x86_64}.pkg.tar"